# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: MIT

---
header:
  comment: on-failure
  license:
    spdx-id: MIT
    copyright-owner: Cẩm nang NQDEV. All Rights Reserved.

    content: |
      # Copyright Cẩm nang NQDEV. All Rights Reserved.
      # SPDX-License-Identifier: MIT

  paths:
    - '**/Dockerfile'
